import type { PurchaseRequestWithRelations } from '@db/schema';

export interface CompanyBranding {
  name: string;
  logo?: string; // base64 encoded logo
  logoMimeType?: string;
  primaryColor: [number, number, number]; // RGB values
  secondaryColor: [number, number, number];
  accentColor: [number, number, number];
  headerStyle?: 'modern' | 'classic' | 'minimal';
  footerText?: string;
}

export interface TemplateConfig {
  branding: CompanyBranding;
  layout: 'bento' | 'classic' | 'compact';
  showLogo: boolean;
  headerHeight?: number;
  footerHeight?: number;
}

// Default branding configuration
export const defaultBranding: CompanyBranding = {
  name: 'Procurement Management System',
  primaryColor: [113, 86, 162], // Purple
  secondaryColor: [245, 245, 250], // Light purple
  accentColor: [25, 17, 96], // Dark purple
  headerStyle: 'modern',
  footerText: 'Generated by Procurement Management System'
};

// Helper function to convert hex color to RGB array
export function hexToRgb(hex: string): [number, number, number] {
  try {
    // Remove # if present
    hex = hex.replace(/^#/, '');

    // Handle shorthand hex (e.g. #FFF)
    if (hex.length === 3) {
      hex = hex.split('').map(c => c + c).join('');
    }

    // Parse the hex values
    const bigint = parseInt(hex, 16);
    const r = (bigint >> 16) & 255;
    const g = (bigint >> 8) & 255;
    const b = bigint & 255;

    return [r, g, b];
  } catch (error) {
    console.error('Error converting hex to RGB:', error, 'hex:', hex);
    return [0, 0, 0]; // Return black as fallback
  }
}

// Template-specific styling functions
export function applyHeaderStyle(doc: any, config: TemplateConfig, pageWidth: number) {
  const { branding, headerHeight = 35 } = config;
  const { primaryColor, name, headerStyle, logo, logoMimeType } = branding;
  let currentY = 0;

  // Add company logo ABOVE header (top left corner)
  if (config.showLogo && logo) {
    try {
      const logoWidth = 30;
      const logoHeight = 20;
      doc.addImage(
        `data:${logoMimeType};base64,${logo}`,
        logoMimeType?.split('/')[1].toUpperCase() || 'PNG',
        12,
        currentY + 5,
        logoWidth,
        logoHeight
      );
      // Move header down after logo
      currentY += logoHeight + 8;
    } catch (error) {
      console.error('Error adding logo to PDF:', error);
      // Continue without logo
      currentY += 5;
    }
  } else {
    currentY += 5;
  }

  // Modern style with solid background positioned below logo
  if (headerStyle === 'modern') {
    // Draw background below logo
    const reducedHeaderHeight = headerHeight * 0.8; // Reduce header size by 20%
    doc.setFillColor(...primaryColor);
    doc.rect(0, currentY, pageWidth, reducedHeaderHeight, 'F');

    // Header text and decorative elements
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16); // Reduced from 18
    doc.setFont('helvetica', 'bold');
    
    // Main title
    doc.text(name, 12, currentY + 12);
    
    // Subtitle
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('PURCHASE REQUEST', 12, currentY + 22);

    // Add decorative line
    doc.setDrawColor(255, 255, 255);
    doc.setLineWidth(0.5);
    doc.line(12, currentY + reducedHeaderHeight - 3, pageWidth - 12, currentY + reducedHeaderHeight - 3);
  } else {
      // No logo - centered text with decorative elements
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text(name, pageWidth / 2, 17, { align: 'center' });

      // Add decorative lines
      doc.setDrawColor(255, 255, 255);
      doc.setLineWidth(0.5);
      doc.line(20, 20, pageWidth - 20, 20);
    }
  } else if (headerStyle === 'classic') {
    // Classic style with sophisticated border positioned below logo
    const reducedHeaderHeight = headerHeight * 0.8; // Reduce header size by 20%
    doc.setDrawColor(...primaryColor);
    doc.setLineWidth(1);
    doc.line(0, currentY + reducedHeaderHeight, pageWidth, currentY + reducedHeaderHeight);

    // Add subtle top border
    doc.setLineWidth(0.5);
    doc.line(0, currentY + 2, pageWidth, currentY + 2);

    // Header text
    doc.setTextColor(...primaryColor);
    doc.setFontSize(14); // Reduced from 16
    doc.setFont('helvetica', 'bold');
    doc.text(name, pageWidth / 2, currentY + 12, { align: 'center' });
    
    // Subtitle
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('PURCHASE REQUEST', pageWidth / 2, currentY + 20, { align: 'center' });
  } else {
    // Minimal style with subtle elements positioned below logo
    const reducedHeaderHeight = headerHeight * 0.8; // Reduce header size by 20%
    
    // Header text
    doc.setTextColor(...primaryColor);
    doc.setFontSize(14); // Reduced from 16
    doc.setFont('helvetica', 'bold');
    doc.text(name, pageWidth / 2, currentY + 12, { align: 'center' });
    
    // Subtitle
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('PURCHASE REQUEST', pageWidth / 2, currentY + 20, { align: 'center' });

    // Add subtle bottom border for minimal style
    doc.setDrawColor(...primaryColor);
    doc.setLineWidth(0.2);
    doc.line(20, currentY + (headerHeight * 0.8) - 2, pageWidth - 20, currentY + (headerHeight * 0.8) - 2);
  }

  // Return the Y position where content should continue
  return currentY + (headerHeight * 0.8) + 5;
}

export function applyFooterStyle(doc: any, config: TemplateConfig, pageWidth: number, pageHeight: number) {
  const { branding, footerHeight = 25 } = config;
  const { footerText, primaryColor, accentColor } = branding;

  const footerY = pageHeight - footerHeight;

  // Add subtle top border
  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.2);
  doc.line(20, footerY + 5, pageWidth - 20, footerY + 5);

  // Add footer text
  doc.setTextColor(...accentColor);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(
    footerText || 'Generated by Procurement Management System',
    pageWidth / 2,
    footerY + 15,
    { align: 'center' }
  );

  // Add page number
  doc.text(
    `Page ${doc.internal.getNumberOfPages()}`,
    pageWidth - 20,
    footerY + 15,
    { align: 'right' }
  );

  return footerHeight;
}

// Helper function to create tile backgrounds
export function createTileBackground(doc: any, config: TemplateConfig, x: number, y: number, width: number, height: number) {
  const { branding } = config;

  // Set background color
  doc.setFillColor(...branding.secondaryColor);
  doc.roundedRect(x, y, width, height, 3, 3, 'F');

  // Add subtle border
  doc.setDrawColor(...branding.primaryColor);
  doc.setLineWidth(0.2);
  doc.roundedRect(x, y, width, height, 3, 3, 'S');

  // Add subtle shadow effect
  doc.setDrawColor(...branding.primaryColor.map(c => Math.max(0, c - 40)));
  doc.setLineWidth(0.1);
  doc.roundedRect(x + 0.5, y + 0.5, width, height, 3, 3, 'S');
}