import type { PurchaseRequestWithRelations } from '@db/schema';

export interface CompanyBranding {
  name: string;
  logo?: string; // base64 encoded logo
  logoMimeType?: string;
  primaryColor: [number, number, number]; // RGB values
  secondaryColor: [number, number, number];
  accentColor: [number, number, number];
  headerStyle?: 'modern' | 'classic' | 'minimal';
  footerText?: string;
}

export interface TemplateConfig {
  branding: CompanyBranding;
  layout: 'bento' | 'classic' | 'compact';
  showLogo: boolean;
  headerHeight?: number;
  footerHeight?: number;
}

// Default branding configuration
export const defaultBranding: CompanyBranding = {
  name: 'Procurement Management System',
  primaryColor: [113, 86, 162], // Purple
  secondaryColor: [245, 245, 250], // Light purple
  accentColor: [25, 17, 96], // Dark purple
  headerStyle: 'modern',
  footerText: 'Generated by Procurement Management System'
};

// Helper function to convert hex color to RGB array
export function hexToRgb(hex: string): [number, number, number] | null {
  const shorthandRegex = /^#?([a-f\d])([a-f\d])([a-f\d])$/i;
  hex = hex.replace(shorthandRegex, (_m, r, g, b) => r + r + g + g + b + b);

  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? [
    parseInt(result[1], 16),
    parseInt(result[2], 16),
    parseInt(result[3], 16)
  ] : null;
}

// Template-specific styling functions
export function applyHeaderStyle(doc: any, config: TemplateConfig, pageWidth: number) {
  const { branding, headerHeight = 25 } = config;
  const { primaryColor, name, headerStyle, logo, logoMimeType } = branding;

  // Apply header background
  doc.setFillColor(...primaryColor);

  if (headerStyle === 'modern') {
    // Modern style with gradient effect
    doc.rect(0, 0, pageWidth, headerHeight, 'F');

    // Add logo if available
    if (config.showLogo && logo) {
      try {
        doc.addImage(
          `data:${logoMimeType};base64,${logo}`,
          logoMimeType?.split('/')[1].toUpperCase() || 'PNG',
          10,
          5,
          15,
          15
        );
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(16);
        doc.text(name, 30, 15);
      } catch (error) {
        console.error('Error adding logo to PDF:', error);
        // Fallback to centered text if logo fails
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(16);
        doc.text(name, pageWidth / 2, 15, { align: 'center' });
      }
    } else {
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(16);
      doc.text(name, pageWidth / 2, 15, { align: 'center' });
    }
  } else if (headerStyle === 'classic') {
    // Classic style with border
    doc.setDrawColor(...primaryColor);
    doc.setLineWidth(0.5);
    doc.line(0, headerHeight, pageWidth, headerHeight);

    if (config.showLogo && logo) {
      try {
        doc.addImage(
          `data:${logoMimeType};base64,${logo}`,
          logoMimeType?.split('/')[1].toUpperCase() || 'PNG',
          10,
          5,
          15,
          15
        );
      } catch (error) {
        console.error('Error adding logo to PDF:', error);
      }
    }
    doc.setTextColor(...primaryColor);
    doc.setFontSize(14);
    doc.text(name, pageWidth / 2, 15, { align: 'center' });
  } else {
    // Minimal style
    if (config.showLogo && logo) {
      try {
        doc.addImage(
          `data:${logoMimeType};base64,${logo}`,
          logoMimeType?.split('/')[1].toUpperCase() || 'PNG',
          10,
          5,
          15,
          15
        );
      } catch (error) {
        console.error('Error adding logo to PDF:', error);
      }
    }
    doc.setTextColor(...primaryColor);
    doc.setFontSize(14);
    doc.text(name, pageWidth / 2, 15, { align: 'center' });
  }

  return headerHeight;
}

export function applyFooterStyle(doc: any, config: TemplateConfig, pageWidth: number, pageHeight: number) {
  const { branding, footerHeight = 15 } = config;
  const { footerText, primaryColor } = branding;

  const footerY = pageHeight - footerHeight;

  doc.setTextColor(...primaryColor);
  doc.setFontSize(8);
  doc.text(
    footerText || 'Generated by Procurement Management System',
    pageWidth / 2,
    footerY + 10,
    { align: 'center' }
  );

  return footerHeight;
}

// Helper function to create tile backgrounds
export function createTileBackground(doc: any, config: TemplateConfig, x: number, y: number, width: number, height: number) {
  const { branding } = config;

  // Create subtle gradient effect
  doc.setFillColor(...branding.secondaryColor);
  doc.roundedRect(x, y, width, height, 2, 2, 'F');

  // Add subtle border
  doc.setDrawColor(...branding.primaryColor);
  doc.setLineWidth(0.1);
  doc.roundedRect(x, y, width, height, 2, 2, 'S');
}