import type { PurchaseRequestWithRelations } from '@db/schema';

export interface CompanyBranding {
  name: string;
  logo?: string; // base64 encoded logo
  logoMimeType?: string;
  primaryColor: [number, number, number]; // RGB values
  secondaryColor: [number, number, number];
  accentColor: [number, number, number];
  headerStyle?: 'modern' | 'classic' | 'minimal';
  footerText?: string;
}

export interface TemplateConfig {
  branding: CompanyBranding;
  layout: 'bento' | 'classic' | 'compact';
  showLogo: boolean;
  headerHeight?: number;
  footerHeight?: number;
}

// Default branding configuration
export const defaultBranding: CompanyBranding = {
  name: 'Procurement Management System',
  primaryColor: [113, 86, 162], // Purple
  secondaryColor: [245, 245, 250], // Light purple
  accentColor: [25, 17, 96], // Dark purple
  headerStyle: 'modern',
  footerText: 'Generated by Procurement Management System'
};

// Helper function to convert hex color to RGB array
export function hexToRgb(hex: string): [number, number, number] {
  try {
    // Remove # if present
    hex = hex.replace(/^#/, '');

    // Handle shorthand hex (e.g. #FFF)
    if (hex.length === 3) {
      hex = hex.split('').map(c => c + c).join('');
    }

    // Parse the hex values
    const bigint = parseInt(hex, 16);
    const r = (bigint >> 16) & 255;
    const g = (bigint >> 8) & 255;
    const b = bigint & 255;

    return [r, g, b];
  } catch (error) {
    console.error('Error converting hex to RGB:', error, 'hex:', hex);
    return [0, 0, 0]; // Return black as fallback
  }
}

// Template-specific styling functions
export function applyHeaderStyle(doc: any, config: TemplateConfig, pageWidth: number) {
  const { branding, headerHeight = 35 } = config;
  const { primaryColor, name, headerStyle, logo, logoMimeType } = branding;

  // Modern style with solid background
  if (headerStyle === 'modern') {
    // Draw background
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, pageWidth, headerHeight, 'F');

    // Add logo if available
    if (config.showLogo && logo) {
      try {
        doc.addImage(
          `data:${logoMimeType};base64,${logo}`,
          logoMimeType?.split('/')[1].toUpperCase() || 'PNG',
          12,
          5,
          20,
          20
        );
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.text(name, 40, 17);

        // Add decorative line
        doc.setDrawColor(255, 255, 255);
        doc.setLineWidth(0.5);
        doc.line(40, 20, pageWidth - 20, 20);
      } catch (error) {
        console.error('Error adding logo to PDF:', error);
        // Fallback to centered text with decorative elements
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(20);
        doc.setFont('helvetica', 'bold');
        doc.text(name, pageWidth / 2, 17, { align: 'center' });

        // Add decorative lines
        doc.setDrawColor(255, 255, 255);
        doc.setLineWidth(0.5);
        doc.line(20, 20, pageWidth - 20, 20);
      }
    } else {
      // No logo - centered text with decorative elements
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text(name, pageWidth / 2, 17, { align: 'center' });

      // Add decorative lines
      doc.setDrawColor(255, 255, 255);
      doc.setLineWidth(0.5);
      doc.line(20, 20, pageWidth - 20, 20);
    }
  } else if (headerStyle === 'classic') {
    // Classic style with sophisticated border
    doc.setDrawColor(...primaryColor);
    doc.setLineWidth(1);
    doc.line(0, headerHeight, pageWidth, headerHeight);

    // Add subtle top border
    doc.setLineWidth(0.5);
    doc.line(0, 2, pageWidth, 2);

    if (config.showLogo && logo) {
      try {
        doc.addImage(
          `data:${logoMimeType};base64,${logo}`,
          logoMimeType?.split('/')[1].toUpperCase() || 'PNG',
          12,
          5,
          20,
          20
        );
      } catch (error) {
        console.error('Error adding logo to PDF:', error);
      }
    }
    doc.setTextColor(...primaryColor);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(name, pageWidth / 2, 17, { align: 'center' });
  } else {
    // Minimal style with subtle elements
    if (config.showLogo && logo) {
      try {
        doc.addImage(
          `data:${logoMimeType};base64,${logo}`,
          logoMimeType?.split('/')[1].toUpperCase() || 'PNG',
          12,
          5,
          20,
          20
        );
      } catch (error) {
        console.error('Error adding logo to PDF:', error);
      }
    }
    doc.setTextColor(...primaryColor);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(name, pageWidth / 2, 17, { align: 'center' });

    // Add subtle bottom border
    doc.setDrawColor(...primaryColor);
    doc.setLineWidth(0.2);
    doc.line(20, headerHeight - 2, pageWidth - 20, headerHeight - 2);
  }

  return headerHeight;
}

export function applyFooterStyle(doc: any, config: TemplateConfig, pageWidth: number, pageHeight: number) {
  const { branding, footerHeight = 25 } = config;
  const { footerText, primaryColor, accentColor } = branding;

  const footerY = pageHeight - footerHeight;

  // Add subtle top border
  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.2);
  doc.line(20, footerY + 5, pageWidth - 20, footerY + 5);

  // Add footer text
  doc.setTextColor(...accentColor);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(
    footerText || 'Generated by Procurement Management System',
    pageWidth / 2,
    footerY + 15,
    { align: 'center' }
  );

  // Add page number
  doc.text(
    `Page ${doc.internal.getNumberOfPages()}`,
    pageWidth - 20,
    footerY + 15,
    { align: 'right' }
  );

  return footerHeight;
}

// Helper function to create tile backgrounds
export function createTileBackground(doc: any, config: TemplateConfig, x: number, y: number, width: number, height: number) {
  const { branding } = config;

  // Set background color
  doc.setFillColor(...branding.secondaryColor);
  doc.roundedRect(x, y, width, height, 3, 3, 'F');

  // Add subtle border
  doc.setDrawColor(...branding.primaryColor);
  doc.setLineWidth(0.2);
  doc.roundedRect(x, y, width, height, 3, 3, 'S');

  // Add subtle shadow effect
  doc.setDrawColor(...branding.primaryColor.map(c => Math.max(0, c - 40)));
  doc.setLineWidth(0.1);
  doc.roundedRect(x + 0.5, y + 0.5, width, height, 3, 3, 'S');
}