import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { PDFCustomizationForm } from '@/components/PDFCustomizationForm';
import PDFBrandingUploader from '@/components/PDFBrandingUploader';
import { Tabs as TabsUI, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';

export default function PDFConfiguration() {
  return (
    <div className="container mx-auto py-8">
      <h1 className="text-3xl font-bold mb-6">PDF Configuration</h1>
      <Card className="mb-6">
        <CardHeader>
          <CardTitle>PDF Generation Settings</CardTitle>
          <CardDescription>
            Configure how PDF documents are generated and displayed across the application.
            Changes will affect all future PDFs generated by the system.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <TabsUI defaultValue="appearance" className="w-full">
            <TabsList className="grid w-full grid-cols-2">
              <TabsTrigger value="appearance">Appearance Settings</TabsTrigger>
              <TabsTrigger value="branding">Branding & Images</TabsTrigger>
            </TabsList>
            <TabsContent value="appearance" className="p-4">
              <PDFCustomizationForm />
            </TabsContent>
            <TabsContent value="branding" className="p-4">
              <PDFBrandingUploader />
            </TabsContent>
          </TabsUI>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>PDF Preview & Testing</CardTitle>
          <CardDescription>
            Generate a test PDF document to see how your settings will appear.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center">
          <p className="text-center mb-6 text-gray-600">
            Preview functionality coming soon. Changes to configuration will be applied
            to all PDF exports immediately.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}