import { db } from "./index";
import { vendors } from "./schema";

async function seedVendors() {
  console.log("🌱 Starting Official Vendor Seeding...");

  try {
    // Step A: Wipe existing legacy/dummy vendors
    // User confirmed PRs are purged, so no FK violations expected.
    console.log("🧹 Purging existing vendor records...");
    await db.delete(vendors);

    // Step B: Official Vendor Data Mapping
    const officialVendors = [
      {
        companyName: "Doha Event Solutions WLL",
        contactPerson: "Ahmed Al-Kuwari",
        email: "ahmed@dohaevents.qa",
        contactNumber: "+974 55123456",
        address: "West Bay, Doha",
        bankName: "Qatar National Bank",
        branchName: "West Bay Branch",
        accountNumber: "001234567890",
        ibanNumber: "QA12QNBA0000001234567890",
        taxNumber: "QA-VAT-00123",
        registrationNumber: "CR-987654",
        complianceScore: 92,
        remarks: "Reliable vendor. Good response time.",
        status: "active",
        category: "events",
      },
      {
        companyName: "Gulf Creative Media",
        contactPerson: "Sara Al-Mansoori",
        email: "sara@gulfcreative.qa",
        contactNumber: "+974 55345678",
        address: "Lusail Marina",
        bankName: "Commercial Bank of Qatar",
        branchName: "Lusail Branch",
        accountNumber: "002345678901",
        ibanNumber: "QA98CBQA0000002345678901",
        taxNumber: "QA-VAT-00234",
        registrationNumber: "CR-876543",
        complianceScore: 88,
        remarks: "Strong design team. Premium pricing.",
        status: "active",
        category: "media",
      },
      {
        companyName: "Qatar Inflatable Factory",
        contactPerson: "Imran Khan",
        email: "imran@qif.qa",
        contactNumber: "+974 55567890",
        address: "Industrial Area",
        bankName: "Doha Bank QPSC",
        branchName: "Industrial Area Branch",
        accountNumber: "003456789012",
        ibanNumber: "QA56DHBK0000003456789012",
        taxNumber: "QA-VAT-00345",
        registrationNumber: "CR-765432",
        complianceScore: 90,
        remarks: "Manufacturing expert. Fast production.",
        status: "active",
        category: "equipment",
      },
      {
        companyName: "Desert Tech Rentals",
        contactPerson: "Khalid Al-Hajri",
        email: "khalid@deserttech.qa",
        contactNumber: "+974 55987654",
        address: "Al Wakrah",
        bankName: "Al Rayan Bank",
        branchName: "Wakrah Branch",
        accountNumber: "004567890123",
        ibanNumber: "QA34MSRQ0000004567890123",
        taxNumber: "QA-VAT-00456",
        registrationNumber: "CR-654321",
        complianceScore: 85,
        remarks: "AV & tech rental. Reliable inventory.",
        status: "active",
        category: "technology",
      },
      {
        companyName: "Aspire Entertainment Group",
        contactPerson: "Noor Al-Thani",
        email: "noor@aspireent.qa",
        contactNumber: "+974 55211223",
        address: "Aspire Zone",
        bankName: "Qatar Islamic Bank",
        branchName: "Aspire Branch",
        accountNumber: "005678901234",
        ibanNumber: "QA78QIBK0000005678901234",
        taxNumber: "QA-VAT-00567",
        registrationNumber: "CR-543210",
        complianceScore: 94,
        remarks: "Event production. Premium client base.",
        status: "active",
        category: "entertainment",
      },
      {
        companyName: "Urban Branding Studio",
        contactPerson: "Zain Ahmed",
        email: "zain@urbanbranding.qa",
        contactNumber: "+974 55822334",
        address: "Msheireb Downtown",
        bankName: "Dukhan Bank",
        branchName: "Msheireb Branch",
        accountNumber: "006789012345",
        ibanNumber: "QA90DUBK0000006789012345",
        taxNumber: "QA-VAT-00678",
        registrationNumber: "CR-432109",
        complianceScore: 89,
        remarks: "Branding specialist. Creative concepts.",
        status: "active",
        category: "branding",
      },
      {
        companyName: "Falcon Logistics Qatar",
        contactPerson: "Hassan Al-Sulaiti",
        email: "hassan@falconlog.qa",
        contactNumber: "+974 55633445",
        address: "Ras Bufontas",
        bankName: "Qatar National Bank",
        branchName: "Airport Branch",
        accountNumber: "007890123456",
        ibanNumber: "QA11QNBA0000007890123456",
        taxNumber: "QA-VAT-00789",
        registrationNumber: "CR-321098",
        complianceScore: 91,
        remarks: "Logistics support. On-time delivery.",
        status: "active",
        category: "logistics",
      },
      {
        companyName: "Pearl Hospitality Services",
        contactPerson: "Lina Joseph",
        email: "lina@pearlhospitality.qa",
        contactNumber: "+974 55744556",
        address: "The Pearl Qatar",
        bankName: "Commercial Bank of Qatar",
        branchName: "Pearl Branch",
        accountNumber: "008901234567",
        ibanNumber: "QA22CBQA0000008901234567",
        taxNumber: "QA-VAT-00890",
        registrationNumber: "CR-210987",
        complianceScore: 87,
        remarks: "Catering services. High quality food.",
        status: "active",
        category: "hospitality",
      },
      {
        companyName: "Skyline Fabrication Works",
        contactPerson: "Tariq Mahmood",
        email: "tariq@skylinefab.qa",
        contactNumber: "+974 55455667",
        address: "Industrial Area",
        bankName: "Doha Bank QPSC",
        branchName: "Industrial Branch",
        accountNumber: "009012345678",
        ibanNumber: "QA33DHBK0000009012345678",
        taxNumber: "QA-VAT-00901",
        registrationNumber: "CR-109876",
        complianceScore: 86,
        remarks: "Fabrication vendor. Cost effective.",
        status: "active",
        category: "fabrication",
      },
      {
        companyName: "Nova Digital Solutions",
        contactPerson: "Fatima Al-Marri",
        email: "fatima@novadigital.qa",
        contactNumber: "+974 55366778",
        address: "Lusail Boulevard",
        bankName: "Qatar Islamic Bank",
        branchName: "Lusail Branch",
        accountNumber: "010123456789",
        ibanNumber: "QA44QIBK0000010123456789",
        taxNumber: "QA-VAT-01012",
        registrationNumber: "CR-998877",
        complianceScore: 93,
        remarks: "Digital marketing. Strong analytics.",
        status: "active",
        category: "digital",
      },
    ];

    console.log(`🚀 Executing bulk insert of ${officialVendors.length} vendors...`);
    await db.insert(vendors).values(officialVendors as any);

    console.log("✅ Seeding complete! PurchaseTracker database synchronized with official vendor roster.");
  } catch (error) {
    console.error("❌ CRITICAL: Seeding failed!", error);
    process.exit(1);
  }
}

seedVendors();
